/*++

Copyright (C) 2024 3MF Consortium (Original Author)

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.1-develop.

Abstract: This is an autogenerated Rust application that demonstrates the
 usage of the Rust bindings of the 3MF Library

Interface version: 2.5.0

*/

use std::ffi::CString;
use std::ptr;

use lib3mf::{
    sPosition, sTriangle, sTransform, Lib3MF_BuildItem, Lib3MF_MeshObject, Lib3MF_Model,
    Lib3MF_Object, Lib3MF_Writer, Wrapper,
};

fn check(err: i32, context: &str) {
    if err != 0 {
        panic!("{} failed with error {}", context, err);
    }
}

fn main() {
    let wrapper = Wrapper::new(None).expect("failed to load library");
    let api = wrapper.api();

    let mut model: Lib3MF_Model = ptr::null_mut();
    let err = unsafe { (api.lib3mf_createmodel)(&mut model) };
    check(err, "CreateModel");

    let mut mesh: Lib3MF_MeshObject = ptr::null_mut();
    let err = unsafe { (api.lib3mf_model_addmeshobject)(model, &mut mesh) };
    check(err, "AddMeshObject");

    let name = CString::new("Box").expect("name");
    let err = unsafe { (api.lib3mf_object_setname)(mesh as Lib3MF_Object, name.as_ptr()) };
    check(err, "SetName");

    let size_x = 100.0f32;
    let size_y = 200.0f32;
    let size_z = 300.0f32;

    let vertices: [sPosition; 8] = [
        sPosition { Coordinates: [0.0, 0.0, 0.0] },
        sPosition { Coordinates: [size_x, 0.0, 0.0] },
        sPosition { Coordinates: [size_x, size_y, 0.0] },
        sPosition { Coordinates: [0.0, size_y, 0.0] },
        sPosition { Coordinates: [0.0, 0.0, size_z] },
        sPosition { Coordinates: [size_x, 0.0, size_z] },
        sPosition { Coordinates: [size_x, size_y, size_z] },
        sPosition { Coordinates: [0.0, size_y, size_z] },
    ];

    let triangles: [sTriangle; 12] = [
        sTriangle { Indices: [2, 1, 0] },
        sTriangle { Indices: [0, 3, 2] },
        sTriangle { Indices: [4, 5, 6] },
        sTriangle { Indices: [6, 7, 4] },
        sTriangle { Indices: [0, 1, 5] },
        sTriangle { Indices: [5, 4, 0] },
        sTriangle { Indices: [2, 3, 7] },
        sTriangle { Indices: [7, 6, 2] },
        sTriangle { Indices: [1, 2, 6] },
        sTriangle { Indices: [6, 5, 1] },
        sTriangle { Indices: [3, 0, 4] },
        sTriangle { Indices: [4, 7, 3] },
    ];

    let err = unsafe {
        (api.lib3mf_meshobject_setgeometry)(
            mesh,
            vertices.len() as u64,
            vertices.as_ptr(),
            triangles.len() as u64,
            triangles.as_ptr(),
        )
    };
    check(err, "SetGeometry");

    let mut transform = sTransform {
        Fields: [[0.0f32; 4]; 3],
    };
    let err = unsafe { (api.lib3mf_getidentitytransform)(&mut transform) };
    check(err, "GetIdentityTransform");

    let mut build_item: Lib3MF_BuildItem = ptr::null_mut();
    let err = unsafe {
        (api.lib3mf_model_addbuilditem)(model, mesh as Lib3MF_Object, &transform, &mut build_item)
    };
    check(err, "AddBuildItem");

    let mut writer: Lib3MF_Writer = ptr::null_mut();
    let ext = CString::new("3mf").expect("ext");
    let err = unsafe { (api.lib3mf_model_querywriter)(model, ext.as_ptr(), &mut writer) };
    check(err, "QueryWriter");

    let filename = CString::new("cube.3mf").expect("filename");
    let err = unsafe { (api.lib3mf_writer_writetofile)(writer, filename.as_ptr()) };
    check(err, "WriteToFile");

    println!("done");
}
